"""initial schema

Revision ID: 6ba206d5374d
Revises: 
Create Date: 2026-08-14 03:14:14.841662
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '6ba206d5374d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('broadcast_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('started_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('hls_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('broadcast_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('idem_key', sa.CHAR(length=36), nullable=False),
    sa.Column('broadcast_id', sa.String(length=32), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idem_key', name='uk_idem'),
    sa.UniqueConstraint('order_id', name='uk_order_id')
    )
    op.create_index('idx_sku_created', 'orders', ['sku_id', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('sku_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('broadcast_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_index('idx_broadcast', 'products', ['broadcast_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_broadcast', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_sku_created', table_name='orders')
    op.drop_table('orders')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
