"""order price snapshot

Revision ID: ccdd5120aa51
Revises: 6ba206d5374d
Create Date: 2026-08-14 07:58:31.344558
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ccdd5120aa51'
down_revision: Union[str, None] = '6ba206d5374d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('unit_price', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'unit_price')
    # ### end Alembic commands ###
